// ============================================================================
// 
// <auto-generated>
// This code was generated by "CSV to resw".
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// 
// ============================================================================

using Microsoft.Windows.ApplicationModel.Resources;

namespace CFileMerge2.Strings;

internal enum Localize
{
	Meta_Language,
	Meta_Translators,
	AppInfo_AppName,
	AppInfo_Distribution_Store,
	AppInfo_Distribution_Zip,
	AppInfo_Description,
	AppInfo_AssociationName,
	File_HelpWithoutExtension,
	File_HistoryWithoutExtension,
	GeneralView_FileTypeSta,
	GeneralView_Error_CannotShowHelp,
	GeneralView_Error_NoAnchor,
	GeneralView_Information_ShowNormalHelp,
	App_Fatal_UnhandledException,
	MainPageViewModel_Error_ButtonBrowseMakeClicked,
	MainPageViewModel_Error_ButtonCfm2SettingsClicked,
	MainPageViewModel_Error_ButtonOpenOutFileClicked,
	MainPageViewModel_Error_ButtonGoClicked,
	MainPageViewModel_Error_ExecuteCfmTagInclude_NoPath,
	MainPageViewModel_Error_ExecuteCfmTagIncludeFolder_NoExist,
	MainPageViewModel_Error_ExecuteCfmTagOutFile_SameFile,
	MainPageViewModel_Warning_ExecuteCfmTagSet_NoEq,
	MainPageViewModel_Warning_ExecuteCfmTagSet_NoName,
	MainPageViewModel_Warning_ExecuteCfmTagVar_NoDeclare,
	MainPageViewModel_Warning_ExecuteCfmTagVar_NoName,
	MainPageViewModel_Error_GetPath_NoPath,
	MainPageViewModel_Error_MenuFlyoutItemRecentMakeClicked,
	MainPageViewModel_Error_MenuFlyoutRecentMakeOpening,
	MainPageViewModel_Error_MenuFlyoutItemFaqClicked,
	MainPageViewModel_Error_MenuFlyoutItemSampleFolderClicked,
	MainPageViewModel_Error_MenuFlyoutItemCreatorSupportClicked,
	MainPageViewModel_Error_MenuFlyoutItemFantiaClicked,
	MainPageViewModel_Error_MenuFlyoutItemAboutClicked,
	MainPageViewModel_Done_MergeAsync,
	MainPageViewModel_Error_MergeAsync,
	MainPageViewModel_Warning_MergeAsync,
	MainPageViewModel_Error_OpenOutFile,
	MainPageViewModel_Warning_ParseCfmTag_NoColon,
	MainPageViewModel_Warning_ParseCfmTag_NotSupported,
	MainPageViewModel_Error_ParseFile_CyclicInclude,
	MainPageViewModel_Error_ParseFile_Empty,
	MainPageViewModel_Error_ParseFile_Encoding,
	MainPageViewModel_Error_ParseFile_NoFile,
	MainPageViewModel_Error_ParseFile_NotSpecified,
	MainPageViewModel_Warning_ParseHxTag_HxId,
	MainPageViewModel_Warning_ParseHxTag_HxNotClose,
	MainPageViewModel_Warning_ParseHxTag_HxRank,
	MainPageViewModel_SrcName_AnchorMakeFile,
	MainPageViewModel_SrcName_AnchorOutFolder,
	MainPageViewModel_SrcName_Tag,
	MainPageViewModel_Updated,
	MainPageViewModel_Warning_Alpha,
	MainPageViewModel_Warning_Beta,
	ProgressWindow_Title,
	ProgressPageViewModel_Confirm_Abort,
	ProgressPageViewModel_Error_ButtonAbortClicked,
	AboutWindow_Title,
	AboutPageViewModel_Error_ButtonCheckUpdateClicked,
	AboutPageViewModel_Error_ButtonHistoryClicked,
	AboutPageViewModel_Error_ButtonOkClicked,
	Cfm2SettingsWindow_Title,
	Cfm2SettingsPageViewModel_Error_ButtonCancelClicked,
	Cfm2SettingsPageViewModel_Error_ButtonDefaultClicked,
	Cfm2SettingsPageViewModel_Error_ButtonOkClicked,
	Cfm2SettingsPageViewModel_Confirm_Default,
	Cfm2SettingsPageViewModel_Error_NavigationViewSelectionChanged,
	Cfm2SettingsNavigationSettingsPageViewModel_Error_CheckProperties_AnchorFile,
	Cfm2SettingsNavigationSettingsPageViewModel_Error_CheckProperties_Toc,
	Cfm2SettingsNavigationMaintenancePage_CheckBoxCheckRss_Content,
	Cfm2SettingsNavigationMaintenancePageViewModel_Done_ButtonBackupClicked,
	Cfm2SettingsNavigationMaintenancePageViewModel_Error_ButtonBackupClicked,
	Cfm2SettingsNavigationMaintenancePageViewModel_Error_ButtonCheckRssClicked,
	Cfm2SettingsNavigationMaintenancePageViewModel_Done_ButtonRestoreClicked,
	Cfm2SettingsNavigationMaintenancePageViewModel_Error_ButtonRestoreClicked,
	Cfm2SettingsNavigationMaintenancePageViewModel_Confirm_CheckRss,
	Cfm2SettingsNavigationMaintenancePageViewModel_Confirm_LoadSettingsArchiveAsync,
	Cfm2SettingsNavigationMaintenancePageViewModel_Error_LoadSettingsArchiveAsync_CannotLoad,
	Cfm2SettingsNavigationMaintenancePageViewModel_Error_LoadSettingsArchiveAsync_CannotLoad2,
	Confirm,
	No,
	Ok,
	Yes,
	Fatal,
	Error,
	Warning,
	Information,
	LatestInfoManager_Ask_AskDisplayLatestAsync,
	LatestInfoManager_Cancel_AskDisplayLatestAsync,
	LatestInfoManager_Error_CheckAsync,
	LatestInfoManager_NoInfo_CheckAsync,
	LatestInfoManager_Error_DisplayLatest_Not,
	LatestInfoManager_Error_DisplayLatest_Part,

}

internal static class LocalizeExtensions
{
	/// <summary>
	/// Returns the most appropriate string value of a resource
	/// </summary>
	/// <param name="localizeKey">Localize enum</param>
	/// <returns></returns>
	public static String Localized(this Localize localizeKey)
	{
		return _resourceLoader.GetString(localizeKey.ToString());
	}

	/// <summary>
	/// ResourceLoader
	/// </summary>
	private static readonly ResourceLoader _resourceLoader = new();
}



